-- =====================================================================
-- 🏛️ SOLUCIONES CONTABLES - SISTEMA OPERATIVO Y BASE DE DATOS DE ALTO RENDIMIENTO
-- =====================================================================
-- Esquema de base de datos de producción optimizado para PostgreSQL y Supabase.
-- Implementa políticas de Row Level Security (RLS) rigurosas, triggers PL/pgSQL
-- para validar consistencia fiscal (CUITs de AFIP), auditoría de seguridad
-- y optimización de índices impositivos de escala.
-- =====================================================================

-- -------------------------------------------------------------
-- 0. TABLA DE AUDITORÍA Y SEGURIDAD (LOGS)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seguridad_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudio_id UUID,
    evento TEXT NOT NULL,
    tabla TEXT NOT NULL,
    registro_id TEXT,
    detalles JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Security Logs
ALTER TABLE public.seguridad_logs ENABLE ROW LEVEL SECURITY;

-- Only authenticated users can insert logs (via database triggers)
CREATE POLICY "Triggers can insert security logs"
    ON public.seguridad_logs
    FOR INSERT
    WITH CHECK (true);

-- Only administrators/owners can read logs
CREATE POLICY "Users can view their own security logs"
    ON public.seguridad_logs
    FOR SELECT
    USING (auth.uid() = estudio_id);


-- -------------------------------------------------------------
-- 1. TABLA DE ESTUDIOS CONTABLES (NUCLEO SAAS MULTI-TENANT)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.estudios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    razon_social TEXT NOT NULL,
    email TEXT NOT NULL,
    arca_model_type TEXT DEFAULT 'hybrid'::text NOT NULL,
    arca_cert_name TEXT,
    arca_cert_uploaded BOOLEAN DEFAULT false NOT NULL,
    -- Progreso del checklist de onboarding (Guía de Instructivo). Antes vivía
    -- disperso en 3 claves de localStorage sin dueño ni sincronización entre
    -- dispositivos del mismo estudio.
    onboarding_task_estudio BOOLEAN DEFAULT false NOT NULL,
    onboarding_import_simulado BOOLEAN DEFAULT false NOT NULL,
    onboarding_iva_validado BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Estudios
ALTER TABLE public.estudios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage their own profile"
    ON public.estudios
    FOR ALL
    USING (auth.uid() = id);


-- -------------------------------------------------------------
-- 2. TABLA DE EMPRESAS CLIENTES (RAZONES SOCIALES)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.empresas (
    id TEXT PRIMARY KEY, -- Formato: 'co-' + timestamp
    estudio_id UUID NOT NULL REFERENCES public.estudios(id) ON DELETE CASCADE,
    razon_social TEXT NOT NULL,
    cuit TEXT NOT NULL, -- Debe estar validado
    tipo TEXT NOT NULL CHECK (tipo IN ('SRL', 'SA', 'SAS', 'Unipersonal', 'Sucesion Indivisa')),
    condicion_iva TEXT NOT NULL CHECK (condicion_iva IN ('Responsable Inscripto', 'Monotributo - Cat A', 'Monotributo - Cat B', 'Monotributo - Cat C', 'Monotributo - Cat D', 'Monotributo - Cat E', 'Monotributo - Cat F', 'Monotributo - Cat G', 'Monotributo - Cat H', 'Monotributo - Cat I', 'Monotributo - Cat J', 'Monotributo - Cat K', 'Exento')),
    actividad TEXT,
    inicio_actividades DATE NOT NULL,
    color TEXT DEFAULT '#0d9488'::text NOT NULL,
    delegation_active BOOLEAN DEFAULT false NOT NULL,
    -- Estado fiscal puntual por empresa, antes disperso en claves sueltas de
    -- localStorage (vmp_consist_ok_, vmp_f2051_presented_, vmp_libro_importado_,
    -- vmp_ret_perc_saldo_, vmp_saldo_favor_, vmp_rt54_asiento_ok_).
    iva_consist_ok BOOLEAN DEFAULT false NOT NULL,
    f2051_presentado BOOLEAN DEFAULT false NOT NULL,
    libro_iva_importado BOOLEAN DEFAULT false NOT NULL,
    ret_perc_saldo_manual NUMERIC(15,2),
    saldo_favor_iva NUMERIC(15,2) DEFAULT 0 NOT NULL,
    rt54_asiento_registrado BOOLEAN DEFAULT false NOT NULL,
    -- Inputs del calculador de valuación de inventario (RT 54).
    rt54_ingresos_periodo NUMERIC(15,2) DEFAULT 0 NOT NULL,
    rt54_stock_final_unidades NUMERIC(15,2) DEFAULT 0 NOT NULL,
    -- Badge de no leídos del inbox de WhatsApp (dato de UI, bajo riesgo).
    wa_unread_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Empresas
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage their own companies"
    ON public.empresas
    FOR ALL
    USING (auth.uid() = estudio_id);


-- -------------------------------------------------------------
-- 3. TABLA DE TRANSACCIONES (LIBRO IVA VENTAS Y COMPRAS CONSOLIDADO)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.transacciones (
    id TEXT PRIMARY KEY, -- Formato: 'v-' o 'c-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('ventas', 'compras')),
    fecha DATE NOT NULL,
    tipo_comprobante TEXT NOT NULL,
    numero TEXT NOT NULL,
    proveedor TEXT,
    cliente TEXT,
    cuit TEXT NOT NULL,
    neto NUMERIC(15,2) NOT NULL CHECK (neto >= 0),
    iva NUMERIC(15,2) NOT NULL CHECK (iva >= 0),
    total NUMERIC(15,2) NOT NULL CHECK (total >= 0),
    es_activo BOOLEAN DEFAULT false NOT NULL, -- Para Bienes de Uso / Retenciones Especiales
    categoria TEXT DEFAULT 'General'::text NOT NULL,
    -- Marca la venta como exenta (Art. 7/8 Ley IVA) para el prorrateo de
    -- crédito fiscal de gastos de uso común (Art. 13 Ley IVA).
    exento BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Un mismo punto de venta + tipo de comprobante no puede repetir número
-- PERO solo para VENTAS (comprobantes propios, numeración que este estudio
-- controla — WSFEv1 rechazaría un CAE duplicado). Las COMPRAS no se
-- restringen: cada proveedor tiene su propia numeración independiente, y
-- dos proveedores distintos bien pueden coincidir en "Factura A 0001-100".
CREATE UNIQUE INDEX IF NOT EXISTS idx_transacciones_numeracion_propia
    ON public.transacciones (empresa_id, tipo_comprobante, numero)
    WHERE (tipo = 'ventas');

-- Habilitar RLS en Transacciones
ALTER TABLE public.transacciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage transactions of their companies"
    ON public.transacciones
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = transacciones.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 4. TABLA DE COMPROBANTES DIGITALIZADOS (TICKETS DE CLIENTES PORTAL MÓVIL)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comprobantes_digitales (
    id TEXT PRIMARY KEY, -- Formato: 't-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    detalle TEXT NOT NULL,
    archivo TEXT NOT NULL, -- URL de almacenamiento seguro
    tipo TEXT DEFAULT 'Compra'::text NOT NULL,
    monto NUMERIC(15,2) NOT NULL CHECK (monto >= 0),
    estado TEXT DEFAULT 'Procesado'::text NOT NULL,
    es_activo BOOLEAN DEFAULT false NOT NULL,
    categoria TEXT DEFAULT 'General'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Comprobantes Digitales
ALTER TABLE public.comprobantes_digitales ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage tickets of their companies"
    ON public.comprobantes_digitales
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = comprobantes_digitales.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 5. TABLA DE LEADS CRM (PROGRAMA DE VENDEDORES / PARTNERS)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    studio TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en Leads
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Permitir inserción anónima para captación de leads en la landing impositiva
CREATE POLICY "Anyone can insert leads"
    ON public.leads
    FOR INSERT
    WITH CHECK (true);

-- Permitir a usuarios autenticados leer los prospectos de ventas
CREATE POLICY "Anyone can view leads"
    ON public.leads
    FOR SELECT
    USING (true);


-- -------------------------------------------------------------
-- 6. TABLA DE RETENCIONES Y PERCEPCIONES
-- -------------------------------------------------------------
-- Reemplaza la clave suelta `vmp_retenciones_<empresaId>`. Cubre las 3
-- fuentes de conciliación reales: factura (Libro Compras), banco (extractos,
-- incluye SIRCREB) y manual (lo que el cliente informa fuera de sistema).
CREATE TABLE IF NOT EXISTS public.retenciones (
    id TEXT PRIMARY KEY, -- Formato: 'r-' + timestamp o 'r-manual-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    agente TEXT NOT NULL,
    cuit TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('PERCEPCIÓN IVA', 'RETENCIÓN IVA', 'PERCEPCIÓN IIBB', 'RETENCIÓN IIBB', 'RETENCIÓN GANANCIAS', 'RETENCIÓN SIRCREB')),
    monto NUMERIC(15,2) NOT NULL CHECK (monto >= 0),
    fuente TEXT NOT NULL DEFAULT 'manual'::text CHECK (fuente IN ('factura', 'banco', 'manual')),
    conciliado BOOLEAN DEFAULT false NOT NULL,
    cert_disponible BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.retenciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage retenciones of their companies"
    ON public.retenciones
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = retenciones.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 7. TABLA DE LIQUIDACIONES DE SUELDOS
-- -------------------------------------------------------------
-- Reemplaza la clave global `vmp_sueldos_liquidaciones` (que mezclaba TODAS
-- las empresas en un único array filtrado en el cliente). Guarda el
-- desglose completo: aportes del empleado, estimación de Ganancias 4ta
-- categoría y cargas de familia declaradas al momento de liquidar.
CREATE TABLE IF NOT EXISTS public.liquidaciones_sueldos (
    id TEXT PRIMARY KEY, -- Formato: 'liq-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    nombre_empleado TEXT NOT NULL,
    cuil TEXT NOT NULL,
    periodo TEXT NOT NULL, -- Formato 'YYYY-MM'
    bruto NUMERIC(15,2) NOT NULL CHECK (bruto > 0),
    aporte_jubilacion NUMERIC(15,2) NOT NULL,
    aporte_pami NUMERIC(15,2) NOT NULL,
    aporte_obra_social NUMERIC(15,2) NOT NULL,
    aporte_sindical NUMERIC(15,2) DEFAULT 0 NOT NULL,
    retencion_ganancias NUMERIC(15,2) DEFAULT 0 NOT NULL,
    conyuge_a_cargo BOOLEAN DEFAULT false NOT NULL,
    hijos_a_cargo INTEGER DEFAULT 0 NOT NULL,
    total_deducciones NUMERIC(15,2) NOT NULL,
    neto NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.liquidaciones_sueldos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage liquidaciones of their companies"
    ON public.liquidaciones_sueldos
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = liquidaciones_sueldos.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 8. TABLA DE ACTIVOS DE USO (RT 54 - BIENES DE USO)
-- -------------------------------------------------------------
-- Reemplaza `vmp_custom_assets_<empresaId>`. Los activos cargados
-- automáticamente desde el Libro de Compras (es_activo = true) NO se
-- duplican acá: se leen en vivo desde `transacciones` y solo estos, los
-- cargados a mano en el sub-libro de RT 54, viven en esta tabla.
CREATE TABLE IF NOT EXISTS public.activos_uso (
    id TEXT PRIMARY KEY, -- Formato: 'cust-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    valor NUMERIC(15,2) NOT NULL CHECK (valor > 0),
    fecha DATE NOT NULL,
    categoria TEXT NOT NULL,
    vida_util_anios INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.activos_uso ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage activos_uso of their companies"
    ON public.activos_uso
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = activos_uso.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 9. TABLA DE AJUSTES POR INFLACIÓN (RT 54 - AxI)
-- -------------------------------------------------------------
-- Reemplaza `vmp_axi_items_<empresaId>`. Igual que en Bienes de Uso, los
-- ítems sincronizados automáticamente desde compras se leen en vivo; solo
-- los rubros patrimoniales cargados a mano viven en esta tabla.
CREATE TABLE IF NOT EXISTS public.ajustes_inflacion (
    id TEXT PRIMARY KEY, -- Formato: 'axi-' + timestamp
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    concepto TEXT NOT NULL,
    origen TEXT NOT NULL, -- Formato 'YYYY-MM' (fecha de origen del rubro)
    valor NUMERIC(15,2) NOT NULL CHECK (valor > 0),
    tipo TEXT NOT NULL CHECK (tipo IN ('patrimonio', 'activo')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.ajustes_inflacion ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage ajustes_inflacion of their companies"
    ON public.ajustes_inflacion
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = ajustes_inflacion.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- -------------------------------------------------------------
-- 10. TABLA DE JURISDICCIONES — CONVENIO MULTILATERAL (IIBB)
-- -------------------------------------------------------------
-- Antes hardcodeado en el array DEFAULT_COMPANIES del cliente (solo la
-- empresa demo de logística lo tenía). Una empresa con una sola fila acá
-- tributa IIBB en régimen local; con más de una, se reparte por
-- Coeficiente Unificado (RG CM 03/04) y se acredita el SIRCREB conciliado
-- de `retenciones` contra el IIBB determinado de cada jurisdicción.
CREATE TABLE IF NOT EXISTS public.jurisdicciones_iibb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id TEXT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    provincia TEXT NOT NULL,
    pct_ingresos NUMERIC(5,2) NOT NULL CHECK (pct_ingresos >= 0 AND pct_ingresos <= 100),
    pct_gastos NUMERIC(5,2) NOT NULL CHECK (pct_gastos >= 0 AND pct_gastos <= 100),
    alicuota_iibb NUMERIC(5,2) NOT NULL CHECK (alicuota_iibb >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (empresa_id, provincia)
);

ALTER TABLE public.jurisdicciones_iibb ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Estudios can manage jurisdicciones of their companies"
    ON public.jurisdicciones_iibb
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresas
            WHERE empresas.id = jurisdicciones_iibb.empresa_id
              AND empresas.estudio_id = auth.uid()
        )
    );


-- ---------------------------------------------------------------------
-- 🛡️ FUNCIONES DE SEGURIDAD Y TRIGGERS DE VALIDACIÓN IMPOSTIVA (CPN AUDIT)
-- ---------------------------------------------------------------------

-- A. Función para validar CUITs de AFIP (Algoritmo Modulo 11 oficial)
CREATE OR REPLACE FUNCTION public.validar_cuit_afip(cuit_input TEXT)
RETURNS BOOLEAN AS $$
DECLARE
    cuit_clean TEXT;
    cuit_array INT[];
    verificador INT;
    acumulado INT := 0;
    multiplicadores INT[] := ARRAY[5, 4, 3, 2, 7, 6, 5, 4, 3, 2];
    i INT;
    calculado INT;
BEGIN
    -- Limpiar guiones o espacios
    cuit_clean := regexp_replace(cuit_input, '[^0-9]', '', 'g');

    -- Si es consumidor final sin registrar o CUIT extranjero simplificado
    IF cuit_clean = '00000000000' OR cuit_clean = '' OR cuit_clean IS NULL THEN
        RETURN TRUE;
    END IF;

    -- Validar longitud exacta de 11 dígitos
    IF length(cuit_clean) != 11 THEN
        RETURN FALSE;
    END IF;

    -- Extraer dígitos a un array
    FOR i IN 1..11 LOOP
        cuit_array[i] := cast(substring(cuit_clean from i for 1) AS INT);
    END LOOP;

    verificador := cuit_array[11];

    -- Aplicar algoritmo módulo 11
    FOR i IN 1..10 LOOP
        acumulado := acumulado + (cuit_array[i] * multiplicadores[i]);
    END LOOP;

    calculado := 11 - (acumulado % 11);

    IF calculado = 11 THEN
        calculado := 0;
    ELSIF calculado = 10 THEN
        calculado := 9;
    END IF;

    RETURN calculado = verificador;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- B. Trigger para validar CUITs al insertar/modificar empresas y transacciones
CREATE OR REPLACE FUNCTION public.trigger_cuit_validation()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT public.validar_cuit_afip(NEW.cuit) THEN
        -- Registrar intento de carga erróneo en auditoría
        INSERT INTO public.seguridad_logs (estudio_id, evento, tabla, registro_id, detalles)
        VALUES (
            COALESCE(auth.uid(), '00000000-0000-0000-0000-000000000000'::uuid),
            'RECHAZO_CUIT_INVALIDO',
            TG_TABLE_NAME::TEXT,
            NEW.id::TEXT,
            jsonb_build_object('cuit_invalido', NEW.cuit, 'razon_social', COALESCE(NEW.razon_social, 'N/A'))
        );
        RAISE EXCEPTION 'Error impositivo AFIP: La CUIT % ingresada posee un dígito verificador inválido bajo Algoritmo Módulo 11.', NEW.cuit;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Aplicar validación a empresas y transacciones
CREATE OR REPLACE TRIGGER on_empresa_validate_cuit
    BEFORE INSERT OR UPDATE ON public.empresas
    FOR EACH ROW EXECUTE FUNCTION public.trigger_cuit_validation();

CREATE OR REPLACE TRIGGER on_transaccion_validate_cuit
    BEFORE INSERT OR UPDATE ON public.transacciones
    FOR EACH ROW EXECUTE FUNCTION public.trigger_cuit_validation();


-- C. Trigger de Aislamiento Tenant Cruzado estricto
CREATE OR REPLACE FUNCTION public.trigger_prevent_cross_tenant_update()
RETURNS TRIGGER AS $$
DECLARE
    owner_id UUID;
BEGIN
    -- Obtener el estudio_id de la empresa asociada a la transacción
    SELECT estudio_id INTO owner_id
    FROM public.empresas
    WHERE empresas.id = NEW.empresa_id;

    -- Si la empresa no pertenece al estudio logueado, levantar alerta de intrusión impositiva
    IF owner_id != auth.uid() THEN
        INSERT INTO public.seguridad_logs (estudio_id, evento, tabla, registro_id, detalles)
        VALUES (
            auth.uid(),
            'ALERTA_INTRUSION_TENANT_CRUZADO',
            TG_TABLE_NAME::TEXT,
            NEW.id::TEXT,
            jsonb_build_object('empresa_id_solicitada', NEW.empresa_id, 'fake_tenant', auth.uid())
        );
        RAISE EXCEPTION 'Alerta de Seguridad SSL: Operación denegada. Intento ilegal de registrar datos en una empresa perteneciente a otro estudio contable.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Aplicar aislamiento a todas las tablas hijas de "empresas"
CREATE OR REPLACE TRIGGER on_transaccion_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.transacciones
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_comprobante_digital_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.comprobantes_digitales
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_retencion_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.retenciones
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_liquidacion_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.liquidaciones_sueldos
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_activo_uso_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.activos_uso
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_ajuste_inflacion_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.ajustes_inflacion
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();

CREATE OR REPLACE TRIGGER on_jurisdiccion_prevent_cross_tenant
    BEFORE INSERT OR UPDATE ON public.jurisdicciones_iibb
    FOR EACH ROW EXECUTE FUNCTION public.trigger_prevent_cross_tenant_update();


-- D. Trigger de Auto-Perfil para nuevos Registros
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.estudios (id, razon_social, email, arca_model_type, arca_cert_name, arca_cert_uploaded)
    VALUES (
        new.id,
        coalesce(new.raw_user_meta_data->>'studio_name', 'Estudio Contable Comahue'),
        new.email,
        'hybrid',
        'estudio_comahue_arca.crt',
        false
    );

    -- Registrar log de auditoría del alta
    INSERT INTO public.seguridad_logs (estudio_id, evento, tabla, registro_id, detalles)
    VALUES (
        new.id,
        'ESTUDIO_REGISTRADO',
        'estudios',
        new.id::TEXT,
        jsonb_build_object('email', new.email)
    );

    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear el Trigger de alta
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- -------------------------------------------------------------
-- 11. ÍNDICES DE ALTO RENDIMIENTO IMPOSITIVO (OLAP OPTIMIZATION)
-- -------------------------------------------------------------
-- Optimización extrema para búsquedas subsegundo en informes mensuales de Libro IVA Digital
CREATE INDEX IF NOT EXISTS idx_transacciones_query_opt
    ON public.transacciones (empresa_id, tipo, fecha DESC);

-- Índice parcial para auditorías preventivas eficientes
CREATE INDEX IF NOT EXISTS idx_transacciones_apoc_parcial
    ON public.transacciones (empresa_id, cuit)
    WHERE (es_activo = true AND categoria = 'APOC');

-- Índices para las tablas nuevas: todas se filtran siempre por empresa_id,
-- y retenciones/liquidaciones además casi siempre por período/fecha.
CREATE INDEX IF NOT EXISTS idx_retenciones_empresa
    ON public.retenciones (empresa_id, fecha DESC);

CREATE INDEX IF NOT EXISTS idx_retenciones_sircreb_pendientes
    ON public.retenciones (empresa_id)
    WHERE (tipo = 'RETENCIÓN SIRCREB' AND conciliado = false);

CREATE INDEX IF NOT EXISTS idx_liquidaciones_empresa_periodo
    ON public.liquidaciones_sueldos (empresa_id, periodo DESC);

CREATE INDEX IF NOT EXISTS idx_activos_uso_empresa
    ON public.activos_uso (empresa_id);

CREATE INDEX IF NOT EXISTS idx_ajustes_inflacion_empresa
    ON public.ajustes_inflacion (empresa_id);

CREATE INDEX IF NOT EXISTS idx_jurisdicciones_empresa
    ON public.jurisdicciones_iibb (empresa_id);
